[required]

process          = 'decode'
lecroy_oscilloscope_model = 'LECROYWS4054HD' # currently only one model implemented
file_path        = '/path/to/file.bin'
save_path        = '/path/to/file.h5'

[optional]

overwrite        = True
