[required]

visualise          = 'waveform' # only 'waveform' as in single waveform so far
file_path          = '/path/to/file.h5'
vis_params         = {
	'baseline_sub'   : 'median',
	'sidebands'      : ((100, 300), (2900, 3100)),
	'negative'       : False}

